### ISSUE TITLE
travis build broken: rakudobrew don't got panda

### ISSUE THREAD

**Issue by zoffixznet** [Altai-man/Slang-Kazu#3]
I don't know what `Panda::Builder` is used for. Are you sure zef doesn't does the Build.pm stuff automatically?

**Comment by Altai-man** [comment]
Well, panda reference was removed, but there are some more fundamental troubles with this slang as for now. I will try to find a solution in my free time, but can't be sure it will be quick enough, unfortunately.

Closing, but feel free to reopen anytime.
